/* oceansafety.info — beach registry
   Single source of truth for the Home search and the Beaches page.
   To add a beach: create its HTML page, then add one line here.
   Fields: name · file · short (used in 'Known Hazards at ___') · type · county · buoy
   Keep `short` under about 14 characters so the hazards heading holds one line.

   Sheltered bay shores (San Francisco Bay and Tomales Bay) carry their NOAA
   tide station number as `buoy` instead of a swell buoy. Their pages show
   wind and tide, not swell, and they show no period reading in the beach list.
   Build: Ethel28 · 119 beaches
*/

const BEACHES = [
  { name:'Thornton State Beach', file:'thornton-beach.html', short:'Thornton', type:'Daly City · Bluffs', county:'San Mateo County', buoy:'46012' },
  { name:'Mussel Rock', file:'mussel-rock.html', short:'Mussel Rock', type:'Daly City · Rock Shelf', county:'San Mateo County', buoy:'46012' },
  { name:'Esplanade Beach', file:'esplanade-beach.html', short:'Esplanade', type:'Pacifica · Bluffs', county:'San Mateo County', buoy:'46012' },
  { name:'Sharp Park Beach', file:'sharp-park-beach.html', short:'Sharp Park', type:'Pacifica · Pebbles & Sandy', county:'San Mateo County', buoy:'46012' },
  { name:'Mori Point', file:'mori-point.html', short:'Mori Point', type:'Pacifica · Bluffs & Rocky', county:'San Mateo County', buoy:'46012' },
  { name:'Rockaway Beach', file:'rockaway-beach.html', short:'Rockaway', type:'Pacifica · Sandy', county:'San Mateo County', buoy:'46012' },
  { name:'Linda Mar', file:'linda-mar.html', short:'Linda Mar', type:'Pacifica · Sandy', county:'San Mateo County', buoy:'46012' },
  { name:'Gray Whale Cove', file:'gray-whale-cove.html', short:'Gray Whale Cove', type:'Montara · Cove', county:'San Mateo County', buoy:'46012' },
  { name:'Montara State Beach', file:'montara-beach.html', short:'Montara', type:'Montara · Sandy', county:'San Mateo County', buoy:'46012' },
  { name:'Fitzgerald Marine Reserve', file:'fitzgerald-marine-reserve.html', short:'Fitzgerald', type:'Moss Beach · Tide Pools & Reef', county:'San Mateo County', buoy:'46012' },
  { name:'Seal Cove', file:'seal-cove.html', short:'Seal Cove', type:'Moss Beach · Cove & Tide Pools', county:'San Mateo County', buoy:'46012' },
  { name:'Mavericks Beach', file:'mavericks-beach.html', short:'Mavericks', type:'Princeton · Reef & Bluffs', county:'San Mateo County', buoy:'46012' },
  { name:'Surfer\'s Beach', file:'surfers-beach.html', short:'Surfer\'s', type:'El Granada · Rocky & Sandy', county:'San Mateo County', buoy:'46012' },
  { name:'Miramar Beach', file:'miramar-beach.html', short:'Miramar', type:'Miramar · Bluffs & Sandy', county:'San Mateo County', buoy:'46012' },
  { name:'Roosevelt Beach', file:'roosevelt-beach.html', short:'Roosevelt', type:'Half Moon Bay · Bluffs & Sandy', county:'San Mateo County', buoy:'46012' },
  { name:'Dunes Beach', file:'dunes-beach.html', short:'Dunes', type:'Half Moon Bay · Sandy & Dunes', county:'San Mateo County', buoy:'46012' },
  { name:'Venice Beach', file:'venice-beach.html', short:'Venice', type:'Half Moon Bay · Bluffs & Sandy', county:'San Mateo County', buoy:'46012' },
  { name:'Francis Beach', file:'francis-beach.html', short:'Francis', type:'Half Moon Bay · Sandy', county:'San Mateo County', buoy:'46012' },
  { name:'Poplar Beach', file:'poplar-beach.html', short:'Poplar', type:'Half Moon Bay · Bluffs & Sandy', county:'San Mateo County', buoy:'46012' },
  { name:'Redondo Beach', file:'redondo-beach.html', short:'Redondo', type:'Half Moon Bay · Tide Pools & Reef', county:'San Mateo County', buoy:'46012' },
  { name:'Manhattan Beach', file:'manhattan-beach.html', short:'Manhattan', type:'Half Moon Bay · Bluffs', county:'San Mateo County', buoy:'46012' },
  { name:'Cowell Ranch', file:'cowell-ranch.html', short:'Cowell Ranch', type:'Half Moon Bay · Remote', county:'San Mateo County', buoy:'46012' },
  { name:'Martins Beach', file:'martins-beach.html', short:'Martins', type:'South of Half Moon Bay · Cove & Bluffs', county:'San Mateo County', buoy:'46012' },
  { name:'Tunitas Creek Beach', file:'tunitas-creek-beach.html', short:'Tunitas Creek', type:'South of Half Moon Bay · Bluffs & Sandy', county:'San Mateo County', buoy:'46012' },
  { name:'San Gregorio', file:'san-gregorio-beach.html', short:'San Gregorio', type:'San Gregorio · Sandy', county:'San Mateo County', buoy:'46012' },
  { name:'Pomponio Beach', file:'pomponio-beach.html', short:'Pomponio', type:'San Gregorio · Sandy', county:'San Mateo County', buoy:'46012' },
  { name:'Pescadero Beach', file:'pescadero-beach.html', short:'Pescadero', type:'Pescadero · Sandy/Rocky', county:'San Mateo County', buoy:'46012' },
  { name:'Pebble Beach, Bean Hollow', file:'pebble-beach-bean-hollow.html', short:'Pebble Beach', type:'Pescadero · Cove & Pebbles', county:'San Mateo County', buoy:'46012' },
  { name:'Bean Hollow', file:'bean-hollow-beach.html', short:'Bean Hollow', type:'Pescadero · Tide Pools', county:'San Mateo County', buoy:'46012' },
  { name:'Pigeon Point', file:'pigeon-point.html', short:'Pigeon Point', type:'Pescadero · Headland', county:'San Mateo County', buoy:'46012' },
  { name:'Gazos Creek Beach', file:'gazos-creek-beach.html', short:'Gazos Creek', type:'Pescadero · Reef & Lagoon', county:'San Mateo County', buoy:'46012' },
  { name:'Franklin Point', file:'franklin-point.html', short:'Franklin Point', type:'Año Nuevo · Rocky & Dunes', county:'San Mateo County', buoy:'46012' },
  { name:'Whitehouse Creek Beach', file:'whitehouse-creek-beach.html', short:'Whitehouse', type:'Año Nuevo · Bluffs & Sandy', county:'San Mateo County', buoy:'46012' },
  { name:'Año Nuevo', file:'ano-nuevo.html', short:'Año Nuevo', type:'Año Nuevo · Reserve', county:'San Mateo County', buoy:'46012' },

  { name:'Ocean Beach', file:'ocean-beach-sf.html', short:'Ocean Beach', type:'Outer Sunset · Open Coast', county:'San Francisco County', buoy:'46026' },
  { name:'Fort Funston', file:'fort-funston-sf.html', short:'Fort Funston', type:'Lake Merced · Bluffs & Sandy', county:'San Francisco County', buoy:'46026' },
  { name:'Sutro Baths / Point Lobos', file:'sutro-baths-point-lobos-sf.html', short:'Sutro Baths', type:'Lands End · Cove & Cliffs', county:'San Francisco County', buoy:'46026' },
  { name:'Mile Rock Beach', file:'mile-rock-beach-sf.html', short:'Mile Rock', type:'Lands End · Cliffs & Rocky', county:'San Francisco County', buoy:'46026' },
  { name:'Eagle\'s Point', file:'eagles-point-sf.html', short:'Eagle\'s Point', type:'Lands End · Cove & Rocky', county:'San Francisco County', buoy:'46026' },
  { name:'China Beach', file:'china-beach-sf.html', short:'China Beach', type:'Sea Cliff · Cove', county:'San Francisco County', buoy:'46026' },
  { name:'Baker Beach', file:'baker-beach-sf.html', short:'Baker Beach', type:'Presidio · Sandy', county:'San Francisco County', buoy:'46026' },
  { name:'Marshall\'s Beach', file:'marshalls-beach-sf.html', short:'Marshall\'s', type:'Presidio · Bluffs & Rocky', county:'San Francisco County', buoy:'46026' },
  { name:'Fort Point', file:'fort-point-sf.html', short:'Fort Point', type:'Presidio · Reef & Rocky', county:'San Francisco County', buoy:'46026' },
  { name:'Crissy Field', file:'crissy-field-sf.html', short:'Crissy Field', type:'Presidio · Bay · Currents', county:'San Francisco County', buoy:'9414290' },
  { name:'Aquatic Park', file:'aquatic-park-sf.html', short:'Aquatic Park', type:'Fisherman\'s Wharf · Cove · Bay', county:'San Francisco County', buoy:'9414290' },
  { name:'Crane Cove Park', file:'crane-cove-park-sf.html', short:'Crane Cove', type:'Dogpatch · Shoreline · Bay', county:'San Francisco County', buoy:'9414290' },
  { name:'Warm Water Cove Park', file:'warm-water-cove-park-sf.html', short:'Warm Water Cove', type:'Dogpatch · Sandy · Bay', county:'San Francisco County', buoy:'9414290' },
  { name:'Islais Creek', file:'islais-creek-sf.html', short:'Islais Creek', type:'Bayview · Shoreline', county:'San Francisco County', buoy:'9414290' },
  { name:'Heron\'s Head Park', file:'herons-head-park-sf.html', short:'Heron\'s Head', type:'Hunters Point · Reef & Rocky · Bay', county:'San Francisco County', buoy:'9414290' },
  { name:'India Basin', file:'india-basin-sf.html', short:'India Basin', type:'Hunters Point · Shoreline · Bay', county:'San Francisco County', buoy:'9414290' },
  { name:'Candlestick Point', file:'candlestick-point-sf.html', short:'Candlestick', type:'Candlestick Point · Shoreline · Bay', county:'San Francisco County', buoy:'9414290' },
  { name:'Clipper Cove Beach', file:'clipper-cove-beach-sf.html', short:'Clipper Cove', type:'Treasure Island · Cove & Sandy · Bay', county:'San Francisco County', buoy:'9414290' },

  { name:'Kirby Cove', file:'kirby-cove.html', short:'Kirby Cove', type:'Marin Headlands · Cove & Bluffs', county:'Marin County', buoy:'46026' },
  { name:'Black Sands Beach', file:'black-sands-beach.html', short:'Black Sands', type:'Marin Headlands · Cliffs & Sandy', county:'Marin County', buoy:'46026' },
  { name:'Rodeo Beach', file:'rodeo-beach.html', short:'Rodeo', type:'Marin Headlands · Pebbles & Cliffs', county:'Marin County', buoy:'46026' },
  { name:'Tennessee Beach', file:'tennessee-beach.html', short:'Tennessee', type:'Marin Headlands · Cove & Pebbles', county:'Marin County', buoy:'46026' },
  { name:'Pirates Cove', file:'pirates-cove.html', short:'Pirates Cove', type:'Marin Headlands · Cove & Cliffs', county:'Marin County', buoy:'46026' },
  { name:'Muir Beach', file:'muir-beach.html', short:'Muir Beach', type:'Marin Headlands · Cove', county:'Marin County', buoy:'46026' },
  { name:'Slide Ranch Beach', file:'slide-ranch-beach.html', short:'Slide Ranch', type:'Muir Beach · Cove & Tide Pools', county:'Marin County', buoy:'46026' },
  { name:'Steep Ravine Beach', file:'steep-ravine-beach.html', short:'Steep Ravine', type:'Mt. Tamalpais Coast · Bluffs & Rocky', county:'Marin County', buoy:'46026' },
  { name:'Red Rock Beach', file:'red-rock-beach.html', short:'Red Rock', type:'Mt. Tamalpais Coast · Cove & Cliffs', county:'Marin County', buoy:'46026' },
  { name:'Stinson Beach', file:'stinson-beach.html', short:'Stinson', type:'Stinson · Sandy · Rip Currents', county:'Marin County', buoy:'46026' },
  { name:'Upton Beach', file:'upton-beach.html', short:'Upton', type:'Stinson Beach · Sandy', county:'Marin County', buoy:'46026' },
  { name:'Seadrift Beach', file:'seadrift-beach.html', short:'Seadrift', type:'Stinson Beach · Lagoon & Sandy', county:'Marin County', buoy:'46026' },
  { name:'Brighton Beach, Bolinas', file:'brighton-beach-bolinas.html', short:'Brighton Beach', type:'Bolinas · Bluffs & Lagoon', county:'Marin County', buoy:'46026' },
  { name:'Agate Beach, Bolinas', file:'agate-beach-bolinas.html', short:'Agate Beach', type:'Bolinas · Tide Pools & Reef', county:'Marin County', buoy:'46026' },
  { name:'RCA Beach', file:'rca-beach.html', short:'RCA', type:'Bolinas · Bluffs & Rocky', county:'Marin County', buoy:'46026' },
  { name:'Palomarin Beach', file:'palomarin-beach.html', short:'Palomarin', type:'Bolinas · Cliffs & Rocky', county:'Marin County', buoy:'46026' },
  { name:'Wildcat Beach & Alamere Falls', file:'wildcat-beach-and-alamere-falls.html', short:'Wildcat Beach', type:'Point Reyes · Bluffs & Cliffs', county:'Marin County', buoy:'46026' },
  { name:'Sculptured Beach', file:'sculptured-beach.html', short:'Sculptured', type:'Drakes Bay · Rocky & Sandy', county:'Marin County', buoy:'46026' },
  { name:'Santa Maria Beach', file:'santa-maria-beach.html', short:'Santa Maria', type:'Drakes Bay · Bluffs & Sandy', county:'Marin County', buoy:'46026' },
  { name:'Limantour Beach', file:'limantour-beach.html', short:'Limantour', type:'Drakes Bay · Sandy & Dunes', county:'Marin County', buoy:'46026' },
  { name:'Drakes Estero Mouth', file:'drakes-estero-mouth.html', short:'Drakes Estero', type:'Drakes Bay · Sandy', county:'Marin County', buoy:'46026' },
  { name:'Drakes Beach', file:'drakes-beach.html', short:'Drakes', type:'Drakes Bay · Cliffs & Sandy', county:'Marin County', buoy:'46026' },
  { name:'Chimney Rock', file:'chimney-rock.html', short:'Chimney Rock', type:'Point Reyes · Cliffs & Rocky', county:'Marin County', buoy:'46026' },
  { name:'Point Reyes Beach', file:'point-reyes-beach.html', short:'Point Reyes', type:'Point Reyes · Exposed · Remote', county:'Marin County', buoy:'46013' },
  { name:'Abbotts Lagoon Beach', file:'abbotts-lagoon-beach.html', short:'Abbotts Lagoon', type:'Great Beach · Lagoon & Sandy', county:'Marin County', buoy:'46013' },
  { name:'Kehoe Beach', file:'kehoe-beach.html', short:'Kehoe', type:'Great Beach · Rocky & Sandy', county:'Marin County', buoy:'46013' },
  { name:'McClures Beach', file:'mcclures-beach.html', short:'McClures', type:'Tomales Point · Tide Pools & Cliffs', county:'Marin County', buoy:'46013' },
  { name:'Heart\'s Desire Beach', file:'hearts-desire-beach.html', short:'Heart\'s Desire', type:'Tomales Bay · Sandy', county:'Marin County', buoy:'9415469' },
  { name:'Indian Beach', file:'indian-beach.html', short:'Indian', type:'Tomales Bay · Sandy', county:'Marin County', buoy:'9415469' },
  { name:'Pebble Beach, Tomales Bay', file:'pebble-beach-tomales-bay.html', short:'Pebble Beach', type:'Tomales Bay · Cove & Pebbles', county:'Marin County', buoy:'9415469' },
  { name:'Shell Beach, Tomales Bay', file:'shell-beach-tomales-bay.html', short:'Shell Beach', type:'Tomales Bay · Sandy', county:'Marin County', buoy:'9415469' },
  { name:'Chicken Ranch Beach', file:'chicken-ranch-beach.html', short:'Chicken Ranch', type:'Tomales Bay · Sandy', county:'Marin County', buoy:'9415469' },
  { name:'Marshall Beach', file:'marshall-beach.html', short:'Marshall', type:'Tomales Bay · Sandy', county:'Marin County', buoy:'9415469' },
  { name:'Millerton Point', file:'millerton-point.html', short:'Millerton Point', type:'Tomales Bay · Sandy', county:'Marin County', buoy:'9415469' },
  { name:'Lawson\'s Landing', file:'lawsons-landing.html', short:'Lawson\'s', type:'Dillon Beach · Sandy & Dunes', county:'Marin County', buoy:'46013' },
  { name:'Dillon Beach', file:'dillon-beach.html', short:'Dillon', type:'Dillon Beach · Rocky & Sandy', county:'Marin County', buoy:'46013' },

  { name:'Doran Beach, Bodega Bay', file:'bodega-bay.html', short:'Bodega Bay', type:'Bodega Bay · Bay and Ocean', county:'Sonoma County', buoy:'46013' },
  { name:'Pinnacle Gulch Beach', file:'pinnacle-gulch-beach.html', short:'Pinnacle Gulch', type:'Bodega Bay · Tide Pools & Rocky', county:'Sonoma County', buoy:'46013' },
  { name:'Campbell Cove', file:'campbell-cove.html', short:'Campbell Cove', type:'Bodega Head · Cove & Sandy', county:'Sonoma County', buoy:'46013' },
  { name:'Bodega Head', file:'bodega-head.html', short:'Bodega Head', type:'Bodega Head · Cliffs & Sandy', county:'Sonoma County', buoy:'46013' },
  { name:'Salmon Creek Beach', file:'salmon-creek-beach.html', short:'Salmon Creek', type:'Bodega · Sandy · Creek Mouth', county:'Sonoma County', buoy:'46013' },
  { name:'Miwok Beach', file:'miwok-beach.html', short:'Miwok', type:'Sonoma Coast · Rocky & Sandy', county:'Sonoma County', buoy:'46013' },
  { name:'Coleman Beach', file:'coleman-beach.html', short:'Coleman', type:'Sonoma Coast · Rocky', county:'Sonoma County', buoy:'46013' },
  { name:'Arched Rock Beach', file:'arched-rock-beach.html', short:'Arched Rock', type:'Sonoma Coast · Bluffs & Rocky', county:'Sonoma County', buoy:'46013' },
  { name:'Marshall Gulch Beach', file:'marshall-gulch-beach.html', short:'Marshall Gulch', type:'Carmet · Cove & Rocky', county:'Sonoma County', buoy:'46013' },
  { name:'Carmet Beach', file:'carmet-beach.html', short:'Carmet', type:'Carmet · Cove & Rocky', county:'Sonoma County', buoy:'46013' },
  { name:'Schoolhouse Beach', file:'schoolhouse-beach.html', short:'Schoolhouse', type:'Carmet · Cove & Rocky', county:'Sonoma County', buoy:'46013' },
  { name:'Portuguese Beach', file:'portuguese-beach.html', short:'Portuguese', type:'Sonoma Coast · Sandy', county:'Sonoma County', buoy:'46013' },
  { name:'Gleason Beach', file:'gleason-beach.html', short:'Gleason', type:'Sonoma Coast · Bluffs & Rocky', county:'Sonoma County', buoy:'46013' },
  { name:'Duncans Landing', file:'duncans-landing.html', short:'Duncans Landing', type:'Sonoma Coast · Cove & Rocky', county:'Sonoma County', buoy:'46013' },
  { name:'Wright\'s Beach', file:'wrights-beach.html', short:'Wright\'s', type:'Sonoma Coast · River Mouth & Sandy', county:'Sonoma County', buoy:'46013' },
  { name:'Shell Beach, Sonoma Coast', file:'shell-beach-sonoma-coast.html', short:'Shell Beach', type:'Jenner · Tide Pools & Bluffs', county:'Sonoma County', buoy:'46013' },
  { name:'Blind Beach', file:'blind-beach.html', short:'Blind', type:'Jenner · Rocky & Sandy', county:'Sonoma County', buoy:'46013' },
  { name:'Goat Rock Beach', file:'goat-rock-beach.html', short:'Goat Rock', type:'Jenner · Rocky · River Mouth', county:'Sonoma County', buoy:'46013' },
  { name:'Russian Gulch', file:'russian-gulch.html', short:'Russian Gulch', type:'Jenner · Cove & Pebbles', county:'Sonoma County', buoy:'46013' },
  { name:'Fort Ross Cove', file:'fort-ross-cove.html', short:'Fort Ross Cove', type:'Fort Ross · Cove & Reef', county:'Sonoma County', buoy:'46013' },
  { name:'Timber Cove', file:'timber-cove.html', short:'Timber Cove', type:'Timber Cove · Cove & Rocky', county:'Sonoma County', buoy:'46013' },
  { name:'Stillwater Cove', file:'stillwater-cove.html', short:'Stillwater Cove', type:'Fort Ross · Cove & Sandy', county:'Sonoma County', buoy:'46013' },
  { name:'Gerstle Cove', file:'gerstle-cove.html', short:'Gerstle Cove', type:'Salt Point State Park · Cove & Tide Pools', county:'Sonoma County', buoy:'46013' },
  { name:'Stump Beach Cove', file:'stump-beach-cove.html', short:'Stump Beach', type:'Salt Point State Park · Cove & Bluffs', county:'Sonoma County', buoy:'46013' },
  { name:'Fisk Mill Cove', file:'fisk-mill-cove.html', short:'Fisk Mill Cove', type:'Salt Point State Park · Cove & Bluffs', county:'Sonoma County', buoy:'46013' },
  { name:'Black Point Beach', file:'black-point-beach.html', short:'Black Point', type:'Sea Ranch · Cove & Cliffs', county:'Sonoma County', buoy:'46013' },
  { name:'Pebble Beach, Sea Ranch', file:'pebble-beach-sea-ranch.html', short:'Pebble Beach', type:'Sea Ranch · Tide Pools & Sandy', county:'Sonoma County', buoy:'46013' },
  { name:'Stengel Beach', file:'stengel-beach.html', short:'Stengel', type:'Sea Ranch · Cove & Bluffs', county:'Sonoma County', buoy:'46013' },
  { name:'Shell Beach, Sea Ranch', file:'shell-beach-sea-ranch.html', short:'Shell Beach', type:'Sea Ranch · Cove & Rocky', county:'Sonoma County', buoy:'46013' },
  { name:'Walk-On Beach', file:'walk-on-beach.html', short:'Walk-On', type:'Sea Ranch · Cove & Sandy', county:'Sonoma County', buoy:'46013' },
  { name:'Gualala Point', file:'gualala-point.html', short:'Gualala Point', type:'Gualala · River Mouth & Sandy', county:'Sonoma County', buoy:'46013' }
];

const COUNTY_ORDER = ['San Mateo County', 'San Francisco County', 'Marin County', 'Sonoma County'];

const COUNTY_META = {
  'San Mateo County':     'Daly City → Año Nuevo · Buoy 46012',
  'San Francisco County': 'Fort Funston → Candlestick · Buoy 46026',
  'Marin County':         'Kirby Cove → Dillon Beach · Buoys 46026 · 46013',
  'Sonoma County':        'Bodega Bay → Gualala · Buoy 46013'
};
